---
- name: Set Up Localstack VM 
  hosts: LOCALSTACK
  tasks:

  - name: Make gpastor sudo passwordless
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%gpastor'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes

  - name: Install & update a list of packages
    ansible.builtin.apt:
      name:
      - python3
      - pip
      - docker.io
      state: latest
      update_cache: yes
    become: yes

  - name: Install python packages
    ansible.builtin.pip: 
      name: 
      - localstack 
      - docker

  - name: Add user to docker group 
    user:
      name: gpastor
      append: yes
      groups: docker
    become: true

  - name: Set authorized keys taken from url
    ansible.posix.authorized_key:
      user: gpastor
      state: present
      key: '{{ item }}'
    with_file:  
    - keys/gpastor.pub
    - keys/ubnt.pub

  - name: pull localstack container
    docker_image: 
      name: localstack/localstack
      tag: latest

