---
- name: Set Up Localstack VM 
  hosts: LOCALSTACK
  tasks:

  - name: Make gpastor sudo passwordless
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%gpastor'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
    become: yes

  - name: Terraform prerequisites
    ansible.builtin.shell: '{{ item }}'
    with_items:
    - 'wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg'
    - 'gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint'
    - 'echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list'
    become: yes

  - name: Install & update a list of packages
    ansible.builtin.apt:
      name:
      - python3
      - gnupg 
      - software-properties-common
      - pip
      - docker.io
      - terraform
      - tree 
      - awscli
      state: latest
      update_cache: yes
    become: yes

  - name: Install python packages
    ansible.builtin.pip: 
      name: 
      - localstack 
      - docker

  - name: Add user to docker group 
    user:
      name: gpastor
      append: yes
      groups: docker
    become: true

  - name: Set authorized keys taken from url
    ansible.posix.authorized_key:
      user: gpastor
      state: present
      key: '{{ item }}'
    with_file:  
    - keys/gpastor.pub
    - keys/ubnt.pub

  - name: pull localstack container
    docker_image: 
      name: localstack/localstack
      tag: latest

