---
- name: Update web servers
  hosts: localhost
  tasks:

  - name: Make gpastor sudo passwordless
    lineinfile:
      path: /etc/sudoers
      state: present
      regexp: '^%gpastor'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'     
    become: yes

  - name: Set hostname
    ansible.builtin.hostname:
      name: UBNT
      use: systemd
    become: yes
      
  - name: Install & update a list of packages
    ansible.builtin.apt:
      name:
      - ansible
      - git
      - docker
      - docker-compose
      - sshpass
      - tree
      state: latest
      update_cache: yes
    become: yes

  - name: create runner folder
    ansible.builtin.file: 
      path: /home/gpastor/homelab/runner 
      state: directory

  - name: download runner
    ansible.builtin.get_url:
      url: https://github.com/actions/runner/releases/download/v2.298.2/actions-runner-linux-x64-2.298.2.tar.gz
      dest: /home/gpastor/homelab/runner/runner.tar.gz

  - name: extract runner
    ansible.builtin.unarchive:
      src: /home/gpastor/homelab/runner/runner.tar.gz
      dest: /home/gpastor/homelab/runner/
      remote_src: yes

  - name: Configure runner
    ansible.builtin.command: ./config.sh --url https://github.com/gpastorbonillo/homelab --token "{{ lookup('file', '../keys/runner.token') }}"
    args:
      chdir: /home/gpastor/homelab/runner
